#!/bin/sh
cd "${0%/*}" || exit    # Run from this directory

wclean findFacesCell
wclean findFace
wclean findCell
wcleanLnIncludeAll

#------------------------------------------------------------------------------
